site_name: MorningSun Documentation
repo_url: https://github.com/ThomasPiton/MorningSun
site_description: Python library for extracting financial data from Morningstar
site_author: Thomas Piton

theme:
  name: material
  features:
    - navigation.tabs
    - content.code.annotate
    - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: amber
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
  - mkdocs-jupyter:
      execute: false

extra_css:
  - assets/custom.css

extra_javascript:
  - https://code.jquery.com/jquery-3.7.1.min.js
  - https://cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js
  - assets/js/dynamic_table.js

nav:
  - Home: index.md
  - Getting Started:
      - Installation: installation.md
      - Usage: usage.md
  - API Reference:
      - Stock: stock.md
      - ETF: etf.md
      - Fund: fund.md
      - Market: market.md
      - News: news.md
      - Time Series: timeseries.md
  - Data:
      - Data Extraction: data_extraction.md
      - Ticker: ticker.md
      - Dynamic Data Table: data/dynamic_table.md
  - Examples:
      - Stock Example: notebooks/stock_examples.ipynb
      - ETF Example: notebooks/etf_examples.ipynb
      - Fund Example: notebooks/fund_examples.ipynb
      - Index Example: notebooks/index_examples.ipynb
      - Market Example: notebooks/market_examples.ipynb
      - News Example: notebooks/news_examples.ipynb
      - TimeSeries Example: notebooks/timeseries_examples.ipynb
