DEFAULT_HEADERS = {
    "accept": "application/json, text/plain, */*",
    "accept-encoding": "gzip, deflate, br",
    "accept-language": "fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7",
    "origin": "https://www.morningstar.fr",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": "Windows",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "cross-site",
    "user-agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/111.0.0.0 Safari/537.36"
    ),
}

URLS = {
    # OTHERS
    "market_calendar":"https://www.morningstar.com/api/v2/markets/calendar",
    "market":"https://www.morningstar.com/api/v2/markets",
    "market_indexes":"https://www.morningstar.com/api/v2/markets/indexes",
    "market_fair_value":"https://www.morningstar.com/api/v2/markets/fair-value",
    "market_movers":"https://www.morningstar.com/api/v2/stores/realtime/movers",
    "market_commodities":"https://www.morningstar.com/api/v2/markets/commodities",
    "market_currencies":"https://www.morningstar.com/api/v2/markets/currencies",
    "list_core_bond_funds":"https://www.morningstar.com/api/v2/lists/core-bond-funds",
    
    
    # SCREEN
    "security_screener":"https://tools.morningstar.co.uk/api/rest.svc/klr5zyak8x/security/screener",
    # TIMESERIES
    "timeseries_":"https://www.us-api.morningstar.com/sal/sal-service/stock/realTime/v3/0P000000GY/data",
    "timeseries_":"https://www.us-api.morningstar.com/QS-markets/chartservice/v2/timeseries",
    "timeseries_":'https://www.morningstar.com/api/v2/stores/realtime/timeseries',
    "timeseries_":"https://www.morningstar.com/api/v2/stores/realtime/quotes",
    "timeseries_":"https://www.us-api.morningstar.com/QS-markets/chartservice/v2/timeseries3",
    "timeseries_":"https://global.morningstar.com/api/v1/en-ca/stores/realtime/quotes",
    "timeseries_":"https://global.morningstar.com/api/v1/en-ca/stores/realtime/movers",
    "timeseries_":"https://global.morningstar.com/api/v1/en-ca/stores/realtime/timeseries",
    # NEWS
    "stories_canada":"https://global.morningstar.com/api/v1/en-ca/stories",
    "news_canada_bond":"https://global.morningstar.com/api/v1/en-ca/sections/bonds",
    "news_canada_etf":"https://global.morningstar.com/api/v1/en-ca/sections/etfs",
    "news_canada_fund":"https://global.morningstar.com/api/v1/en-ca/sections/funds",
    "news_canada_stock":"https://global.morningstar.com/api/v1/en-ca/sections/stocks",
    "news_canada_market":"https://global.morningstar.com/api/v1/en-ca/sections/markets",
    "news_canada_suistainable":"https://global.morningstar.com/api/v1/en-ca/sections/sustainable-investing",
    "news_canada_personal_finance":"https://global.morningstar.com/api/v1/en-ca/sections/personal-finance",
    "news_canada_economy":"https://global.morningstar.com/api/v1/en-ca/sections/economy",
    "news_us_alternative_investments":"https://www.morningstar.com/api/v2/sections/alternative-investments",
    "news_us_financial_advisors":"https://www.morningstar.com/api/v2/sections/financial-advisors",
    "news_us_retirements":"https://www.morningstar.com/api/v2/sections/retirements",
    "news_us_portfolios":"https://www.morningstar.com/api/v2/sections/portfolios",
    "news_us_economy":"https://www.morningstar.com/api/v2/sections/economy",
    "news_us_sustainable_investing":"https://www.morningstar.com/api/v2/sections/sustainable-investing",
    "news_us_personal_finance":"https://www.morningstar.com/api/v2/sections/personal-finance",
    # FUND
    "fund_best_investments":"https://global.morningstar.com/api/v1/en-ca/lists/best-investments/gold-canadian-dividend-and-income-equity-funds",
    "fund_price_alternative_options":"https://api-global.morningstar.com/sal-service/v1/fund/price/alternativeOptions/{F00000T64R}/data",
    "fund_price_selected_option":"https://api-global.morningstar.com/sal-service/v1/fund/price/selectedOption/{F00000T64R}/data",
    "fund_price_cost_illustration":"https://api-global.morningstar.com/sal-service/v1/fund/price/costIllustration/{F00000T64R}/data",
    "fund_disclosure_flag":"https://api-global.morningstar.com/sal-service/v1/fund/disclosureFlag/{F00000T64R}/data",
    "fund_price":"https://api-global.morningstar.com/sal-service/v1/fund/price/v4/{F00000T64R}/data",
    "fund_investment_strategy":"https://api-global.morningstar.com/sal-service/v1/fund/morningstarTake/investmentStrategy/{F00000T64R}/data",
    "fund_strategy_preview":"https://api-global.morningstar.com/sal-service/v1/fund/strategyPreview/{F00000T64R}/data",
    "fund_esg_risk":"https://api-global.morningstar.com/sal-service/v1/fund/esgRisk/{F00000T64R}/data",
    "fund_quote":"https://api-global.morningstar.com/sal-service/v1/fund/quote/v7/{F00000T64R}/data",
    "fund_annual_distribution":"https://api-global.morningstar.com/sal-service/v1/fund/distribution/annual/{F00000T64R}/data",
    "fund_latest_distribution":"https://api-global.morningstar.com/sal-service/v1/fund/distribution/latest/{F00000T64R}/data",
    "fund_esg_product_involvment":"https://api-global.morningstar.com/sal-service/v1/fund/esg/productInvolvement/v1/{F00000T64R}/data",
    "fund_performance_market_volatility_measure":"https://api-global.morningstar.com/sal-service/v1/fund/performance/marketVolatilityMeasure/{F00000T64R}/data",
    "fund_risk_return_summary":"https://api-global.morningstar.com/sal-service/v1/fund/performance/riskReturnSummary/{F00000T64R}/data",
    "fund_risk_score":"https://api-global.morningstar.com/sal-service/v1/fund/performance/riskScore/{F00000T64R}/data",
    "fund_risk_return_scatter_plot":"https://api-global.morningstar.com/sal-service/v1/fund/performance/riskReturnScatterplot/{F00000T64R}/data",
    "fund_risk_volatility":"https://api-global.morningstar.com/sal-service/v1/fund/performance/riskVolatility/{F00000T64R}/data",
    "fund_holding":"https://api-global.morningstar.com/sal-service/v1/fund/portfolio/holding/v2/{F00000T64R}/data",
    "fund_sector":"https://api-global.morningstar.com/sal-service/v1/fund/portfolio/v2/sector/{F00000T64R}/data",
    "fund_asset":"https://api-global.morningstar.com/sal-service/v1/fund/process/asset/v3/{F00000T64R}/data",
    "fund_ownership_zone":"https://api-global.morningstar.com/sal-service/v1/fund/process/ownershipZone/{F00000T64R}/data",
    "fund_factor_profile":"https://api-global.morningstar.com/sal-service/v1/fund/factorProfile/{F00000T64R}/data",
    "fund_stock_style":"https://api-global.morningstar.com/sal-service/v1/fund/process/stockStyle/v2/{F00000T64R}/data",
    "fund_market_cap":"https://api-global.morningstar.com/sal-service/v1/fund/process/marketCap/{F00000T64R}/data",
    "fund_financial_metrics":"https://api-global.morningstar.com/sal-service/v1/fund/process/financialMetrics/{F00000T64R}/data",
    "fund_weighting":"https://api-global.morningstar.com/sal-service/v1/fund/process/weighting/{F00000T64R}/data",
    "fund_equity_style_box_history":"https://api-global.morningstar.com/sal-service/v1/fund/process/equityStyleBoxHistory/{F00000T64R}/data",
    "fund_regional_sector":"https://api-global.morningstar.com/sal-service/v1/fund/portfolio/regionalSector/{F00000T64R}/data",
    "fund_regional_sector_include_countries":"https://api-global.morningstar.com/sal-service/v1/fund/portfolio/regionalSectorIncludeCountries/{F00000T64R}/data",
    "fund_people":"https://api-global.morningstar.com/sal-service/v1/fund/people/{F00000T64R}/data",
    "fund_medalist_rating":"https://api-global.morningstar.com/sal-service/v1/fund/parent/medalistRating/{F00000T64R}/data",
    "fund_medalist_rating_top_funds_up_down":"https://api-global.morningstar.com/sal-service/v1/fund/parent/medalistRating/topfundsUpDown/{F00000T64R}/data",
    "fund_medalist_rating_top_funds":"https://api-global.morningstar.com/sal-service/v1/fund/parent/medalistRating/topfunds/{F00000T64R}/data",
    "fund_mstar_rating":"https://api-global.morningstar.com/sal-service/v1/fund/parent/parentMstarRating/{F00000T64R}/data",
    "fund_mstar_rating_fund_asc":"https://api-global.morningstar.com/sal-service/v1/fund/parent/mstarRating/StarRatingFundAsc/{F00000T64R}/data",
    "fund_mstar_rating_fund_desc":"https://api-global.morningstar.com/sal-service/v1/fund/parent/mstarRating/StarRatingFundDesc/{F00000T64R}/data",
    "fund_security_data":"https://api-global.morningstar.com/sal-service/v1/fund/securityMetaData/{F00000QA9G}",
    # ETF
    "etf_disclosure_flag":"https://api-global.morningstar.com/sal-service/v1/etf/disclosureFlag/{FOUSA06AYT}/data",
    "etf_quote":"https://api-global.morningstar.com/sal-service/v1/etf/quote/v5/{FOUSA06AYT}/data",
    "etf_price":"https://api-global.morningstar.com/sal-service/v1/etf/price/v4/{F00000QA9G}/data",
    "etf_investment_strategy":"https://api-global.morningstar.com/sal-service/v1/etf/morningstarTake/investmentStrategy/{F00000QA9G}/data",
    "etf_esg_risk":"https://api-global.morningstar.com/sal-service/v1/etf/esgRisk/{F00000QA9G}/data",
    "etf_disclosure_flag":"https://api-global.morningstar.com/sal-service/v1/etf/disclosureFlag/{F00000QA9G}/data",
    "etf_performance":"https://api-global.morningstar.com/sal-service/v1/etf/performance/v4/{F00000QA9G}",
    "etf_security_data":"https://api-global.morningstar.com/sal-service/v1/fund/securityMetaData/{F00000QA9G}",
    "etf_performance_table":"https://api-global.morningstar.com/sal-service/v1/etf/performance/table/{F00000QA9G}",
    "etf_price_cost_illustration":"https://api-global.morningstar.com/sal-service/v1/etf/price/costIllustration/{F00000QA9G}/data",
    "etf_realtime_chart_quote":"https://api-global.morningstar.com/sal-service/v1/etf/quote/miniChartRealTimeData/v2/{F00000QA9G}/data",
    "etf_realtime_quote":"https://api-global.morningstar.com/sal-service/v1/etf/quote/realTime/{F00000QA9G}/data",
    "etf_trailing_return":"https://api-global.morningstar.com/sal-service/v1/etf/trailingReturn/v3/{F00000QA9G}/data",
    "etf_esg_product_involvement":"https://api-global.morningstar.com/sal-service/v1/etf/esg/productInvolvement/v1/{F00000QA9G}/data",
    "etf_risk_score":"https://api-global.morningstar.com/sal-service/v1/etf/performance/riskScore/{F00000QA9G}/data",
    "etf_risk_return_summary":"https://api-global.morningstar.com/sal-service/v1/etf/performance/riskReturnSummary/{F00000QA9G}/data",
    "etf_risk_volatility":"https://api-global.morningstar.com/sal-service/v1/etf/performance/riskVolatility/{F00000QA9G}/data",
    "etf_risk_return_scatter_plot":"https://api-global.morningstar.com/sal-service/v1/etf/performance/riskReturnScatterplot/{F00000QA9G}/data",
    "etf_market_volatility_measure":"https://api-global.morningstar.com/sal-service/v1/etf/performance/marketVolatilityMeasure/{F00000QA9G}/data",
    "etf_holding":"https://api-global.morningstar.com/sal-service/v1/etf/portfolio/holding/v2/{F00000QA9G}/data",
    "etf_asset":"https://api-global.morningstar.com/sal-service/v1/etf/process/asset/v3/{F00000QA9G}/data",
    "etf_market_cap":"https://api-global.morningstar.com/sal-service/v1/etf/process/marketCap/{F00000QA9G}/data",
    "etf_factor_profile":"https://api-global.morningstar.com/sal-service/v1/etf/factorProfile/{F00000QA9G}/data",
    "etf_sector":"https://api-global.morningstar.com/sal-service/v1/etf/portfolio/v2/sector/{F00000QA9G}/data",
    "etf_ownership_zone":"https://api-global.morningstar.com/sal-service/v1/etf/process/ownershipZone/{F00000QA9G}/data",
    "etf_stock_style":"https://api-global.morningstar.com/sal-service/v1/etf/process/stockStyle/v2/{F00000QA9G}/data",
    "etf_financial_metrics":"https://api-global.morningstar.com/sal-service/v1/etf/process/financialMetrics/{F00000QA9G}/data",
    "etf_weighting":"https://api-global.morningstar.com/sal-service/v1/etf/process/weighting/{F00000QA9G}/data",
    "etf_equity_style_box_history":"https://api-global.morningstar.com/sal-service/v1/etf/process/equityStyleBoxHistory/{F00000QA9G}/data",
    "etf_regional_sector":"https://api-global.morningstar.com/sal-service/v1/etf/portfolio/regionalSector/{F00000QA9G}/data",
    "etf_regional_sector_include_countries":"https://api-global.morningstar.com/sal-service/v1/etf/portfolio/regionalSectorIncludeCountries/{F00000QA9G}/data",
    "etf_people":"https://api-global.morningstar.com/sal-service/v1/etf/people/{F00000QA9G}/data",
    "etf_top_funds_up_down":"https://api-global.morningstar.com/sal-service/v1/etf/parent/medalistRating/topfundsUpDown/{F00000QA9G}/data",
    "etf_mstar_rating":"https://api-global.morningstar.com/sal-service/v1/etf/parent/medalistRating/{F00000QA9G}/data",
    "etf_mstar_rating_desc":"https://api-global.morningstar.com/sal-service/v1/etf/parent/mstarRating/StarRatingFundDesc/{F00000QA9G}/data",
    "etf_mstar_rating_asc":"https://api-global.morningstar.com/sal-service/v1/etf/parent/mstarRating/StarRatingFundAsc/{F00000QA9G}/data",
    # Index
    "index_performance_table":"https://api-global.morningstar.com/sal-service/v1/index/performance/table/{F00000YLEU}",
    "index_return_data":"https://api-global.morningstar.com/sal-service/v1/index/v1/returnData",
    "index_investments":"https://global.morningstar.com/api/v1/en-ca/investments/indexes/{0P00008IVF}",
    "index_investments_quote":"https://global.morningstar.com/api/v1/en-ca/investments/indexes/{0P00008IVF}/quote",
    "index_disclosure_flag":"https://api-global.morningstar.com/sal-service/v1/index/disclosureFlag/{FOUSA06CZ8}/data",
    "index_risk_return_scatter_plot":"https://api-global.morningstar.com/sal-service/v1/index/performance/riskReturnScatterplot/{FOUSA06CZ8}/data",
    "index_risk_volatility":"https://api-global.morningstar.com/sal-service/v1/index/performance/riskVolatility/{FOUSA06CZ8}/data",
    "index_security_data":"https://api-global.morningstar.com/sal-service/v1/fund/securityMetaData/{FOUSA06CZ8}",
    "index_quote":"https://api-global.morningstar.com/sal-service/v1/index/quote/{FOUSA06CZ8}/data",
    "index_operation":"https://api-global.morningstar.com/sal-service/v1/index/operation/{FOUSA06CZ8}/data",
    "index_description":"https://api-global.morningstar.com/sal-service/v1/index/description/{FOUSA06CZ8}/data",
    "index_performance":"https://api-global.morningstar.com/sal-service/v1/index/performance/v3/{FOUSA06CZ8}",
    "index_asset":"https://api-global.morningstar.com/sal-service/v1/index/process/asset/v3/{FOUSA06CZ8}/data",
    "index_ownership_zone":"https://api-global.morningstar.com/sal-service/v1/index/process/ownershipZone/{FOUSA06CZ8}/data",
    "index_market_cap":"https://api-global.morningstar.com/sal-service/v1/index/process/marketCap/{FOUSA06CZ8}/data",
    "index_stock_style":"https://api-global.morningstar.com/sal-service/v1/index/process/stockStyle/v2/{FOUSA06CZ8}/data",
    "index_financial_metrics":"https://api-global.morningstar.com/sal-service/v1/index/process/financialMetrics/{FOUSA06CZ8}/data",
    "index_factor_profile":"https://api-global.morningstar.com/sal-service/v1/index/factorProfile/{FOUSA06CZ8}/data",
    "index_sector":"https://api-global.morningstar.com/sal-service/v1/index/portfolio/v1/sector/{FOUSA06CZ8}/data",
    "index_fixed_income_style":"https://api-global.morningstar.com/sal-service/v1/index/process/fixedIncomeStyle/{FOUSA06CZ8}/data",
    "index_credit_quality":"https://api-global.morningstar.com/sal-service/v1/index/portfolio/creditQuality/{FOUSA06CZ8}/data",
    "index_coupon_range":"https://api-global.morningstar.com/sal-service/v1/index/process/couponRange/{FOUSA06CZ8}/data",
    "index_fixed_income_style_box_history":"https://api-global.morningstar.com/sal-service/v1/index/process/fixedincomeStyleBoxHistory/{FOUSA06CZ8}/data",
    "index_maturity_schedule":"https://api-global.morningstar.com/sal-service/v1/index/process/maturitySchedule/{FOUSA06CZ8}/data",
    "index_trailing_return":"https://api-global.morningstar.com/sal-service/v1/index/trailingReturn/v4/{FOUSA06CZ8}/data",
    "index_sustainability_country":"https://api-global.morningstar.com/sal-service/v1/index/sustainability/countryReturnData",
    # STOCKS
    "stocks_details":"https://www.morningstar.com/api/v2/stocks/details/",
    "stock_sustainability":"https://api-global.morningstar.com/sal-service/v1/stock/esgRisk/sustainability/{0P0000OQN8}/data",
    "stock_esg_risk":"https://api-global.morningstar.com/sal-service/v1/stock/esgRisk/{0P0000OQN8}/data",
    "stock_company_profile":"https://api-global.morningstar.com/sal-service/v1/stock/companyProfile/{0P0000OQN8}",
    "stock_overview":"https://api-global.morningstar.com/sal-service/v1/stock/equityOverview/{0P0000OQN8}/data",
    "stock_trailingTotalReturns":"https://api-global.morningstar.com/sal-service/v1/stock/trailingTotalReturns/{0P0000OQN8}/data",
    "stock_info":"https://api-global.morningstar.com/sal-service/v1/stock/header/v2/data/{0P000000B7}/securityInfo",
    "stock_key_ratios":"https://api-global.morningstar.com/sal-service/v1/stock/keyratios/{0P0000OQN8}/data",
    "stock_trading_information":"https://api-global.morningstar.com/sal-service/v1/stock/tradingInformation/{0P0000OQN8}/data",
    "stock_summary":"https://api-global.morningstar.com/sal-service/v1/stock/keyMetrics/summary/{0P0000OQN8}",
    "stock_valuation":"https://api-global.morningstar.com/sal-service/v1/stock/valuation/v3/{0P0000OQN8}",
    "stock_growth_table":"https://api-global.morningstar.com/sal-service/v1/stock/keyStats/growthTable/{0P0000OQN8}",
    "stock_profitability_and_efficiency":"https://api-global.morningstar.com/sal-service/v1/stock/keyMetrics/profitabilityAndEfficiency/{0P0000OQN8}",
    "stock_financial_health":"https://api-global.morningstar.com/sal-service/v1/stock/keyMetrics/financialHealth/{0P0000OQN8}",
    "stock_cash_flow":"https://api-global.morningstar.com/sal-service/v1/stock/keyMetrics/cashFlow/{0P0000OQN8}",
    "stock_balance_sheet_detail":"https://api-global.morningstar.com/sal-service/v1/stock/newfinancials/{0P0000OQN8}/balanceSheet/detail",
    "stock_cash_flow_detail":"https://api-global.morningstar.com/sal-service/v1/stock/newfinancials/{0P0000OQN8}/cashFlow/detail",
    "stock_income_statement_detail":"https://api-global.morningstar.com/sal-service/v1/stock/newfinancials/{0P0000OQN8}/incomeStatement/detail",
    "stock_dividends":"https://api-global.morningstar.com/sal-service/v1/stock/dividends/v4/{0P0000OQN8}/data",
    "stock_split":"https://api-global.morningstar.com/sal-service/v1/stock/split/v1/{0P0000OQN8}/data",
    "stock_insider_transaction":"https://api-global.morningstar.com/sal-service/v1/stock/insiders/transactionChart/{0P0000OQN8}/data",
    "stock_insider_key_executives":"https://api-global.morningstar.com/sal-service/v1/stock/insiders/keyExecutives/{0P0000OQN8}/data",
    "stock_transaction_history":"https://api-global.morningstar.com/sal-service/v1/stock/insiders/transactionHistory/{0P0000OQN8}/data",
    "stock_ownership_mutualfund":"https://api-global.morningstar.com/sal-service/v1/stock/ownership/v1/{0P0000OQN8}/OwnershipData/mutualfund/{5}/data",
    "stock_ownership_institution":"https://api-global.morningstar.com/sal-service/v1/stock/ownership/v1/{0P0000OQN8}/OwnershipData/institution/{20}/data",
    "stock_concentrated_owners_institution":"https://api-global.morningstar.com/sal-service/v1/stock/ownership/v1/{0P0000OQN8}/ConcentratedOwners/institution/20/data",
    "stock_concentrated_owners_mutualfund":"https://api-global.morningstar.com/sal-service/v1/stock/ownership/v1/{0P0000OQN8}/ConcentratedOwners/mutualfund/20/data",
    "stock_ownership_buyers_mutualfund":"https://api-global.morningstar.com/sal-service/v1/stock/ownership/v1/{0P0000OQN8}/Buyers/mutualfund/20/data",
    "stock_ownership_buyers_institution":"https://api-global.morningstar.com/sal-service/v1/stock/ownership/v1/{0P0000OQN8}/Buyers/institution/20/data",
    "stock_ownership_sellers_institution":"https://api-global.morningstar.com/sal-service/v1/stock/ownership/v1/{0P0000OQN8}/Sellers/institution/20/data",
    "stock_ownership_sellers_mutualfund":"https://api-global.morningstar.com/sal-service/v1/stock/ownership/v1/{0P0000OQN8}/Sellers/mutualfund/20/data",
    "stock_board_directors":"https://api-global.morningstar.com/sal-service/v1/stock/insiders/boardOfDirectors/{0P0000OQN8}/data",
}

PARAMS = {
    "market_calendar":{
        "date":"",
        "category":""
    },
    "investment_strategy":{
        "languageId": "eg",
        "locale": "eg",
        "clientId": "MDC",
        "benchmarkId": "undefined",
        "component": "sal-mip-strategy",
        "version": "4.69.0"
    },
    "factor_profile":{
        "languageId": "eg",
        "locale": "eg",
        "clientId": "MDC",
        "benchmarkId": "prospectus_primary",
        "component": "sal-mip-star-rating-breakdown",
        "version": "4.69.0"
    },
    "security_screener":{
        'pageSize': 5000,
        'sortOrder': 'LegalName asc',
        'outputType': 'json',
        'version': 1,
        'languageId': 'fr-FR',
        'currencyId': '',
        'universeIds': '',
        'securityDataPoints': 'SecId|Name|Ticker|LegalName|CategoryName|Isin|Universe|Currency|AssetClass',
        'filters': '',
        'term': '',
        'subUniverseId': ''
    }
}

FREQUENCY_MAP = {
    '1min':1,
    '5min':5,
    '10min':10,
    '15min':15,
    '30min':30,
    '60min':60,
    'daily': 'd',
    'weekly': 'w',
    'monthly': 'm'
}

TIMESERIES_COLUMNS = [
    "open", 
    "high", 
    "low", 
    "close", 
    "volume", 
    "previousClose",
    "marketTotalReturn",
    "earning",
    "split",
    "dividend",
    "PE",
    "PS",
    "PB",
    "PCF",
    "EPSRolling",
    "shortInterestRatio"
]

